### ISSUE TITLE
Custom HTML Renderer for Image

### ISSUE THREAD

**Issue by ryantaplin** [nickmcdowall/yatspec#26]
Hey @nickmcdowall 

We have tried implementing a custom renderer for images (as follows):
```
public class RenderImage implements com.googlecode.yatspec.rendering.Renderer<ImagePath> {
    @Override
    public String render(ImagePath o) {
        return "<img src=\""+o.getPath().getName() + "\">";
    }
}
```
It is exhibiting weird behaviour because of the yatspec.js injecting a `<span> constant` based of the following regex. I'm not entirely sure if this is intentional, however currently behaviour results in invalid html being created and therefore ruining the yatspec output.
```
                    {pattern: "\\s[\\w:-]+=", cssClass: "constant" }
```
Raw HTML output looks fine:
```
                            <details class="interaction">
                                <summary class="logKey" logkey="Form_Page">Web Page</summary>
                                <div contenteditable="true" ondblclick="document.execCommand('selectAll',false,null)"
                                     class="logValue highlight ImagePath"><img src="screenshot.png">
                                </div>
                            </details>
```
HTML output when viewed in web browser (with js applied):
```
<img<span class="constant"> src=<span class="quote">"screenshot.png"</span>&gt;
                                </img<span>
```
```
<details class="interaction" open="">
                                <summary class="logKey" logkey="Form_Page">Web Page</summary>
                                <div contenteditable="true" ondblclick="document.execCommand('selectAll',false,null)" class="logValue highlight ImagePath highlighted"><img<span class="constant"> src=<span class="quote">"screenshot.png"</span>&gt;
                                </img<span></div>
                            </details>
```

I suggest to use a negative look ahead to not match on anything preceded by a left angled bracket`<`, you could also consider making it more robust by including a look ahead for a right angled bracket `>`.

I'm not the best at regex but this is as close as I could get it `(?!<|.*>)\s[\w:-]+=` 
https://regexr.com/63e37

I couldn't validate this change would work, I went ahead and removed this regex from the javascript and proceeded to run a build, however it did not cause any of the tests to fail, so i don't currently have any confidence that this change won't break anything.

Note: This is not exclusively limited to the `<img>` tag, but any html tag that uses or requires inline attributes (like so ` someAttribute=`)

What are your thoughts?

**Comment by nickmcdowall** [comment]
Hey @ryantaplin 

Cool - nice idea to add images to the reports. I think the test that checks the output html just doesn't have an example of a quote being rendered but you could add one to see how your alternative regex would work? Or worst case remove the clashing regex since it's only adding minor styling which is less useful than being able to render images for example.

Also a heads up that I am about to deprecate this fork because I'm focusing on the new / replacement project that heavily focuses on the sequence diagrams (and is inspired by yatspec but with a fresh complete rewrite). Perhaps you could consider moving to the new libraries instead? It doesn't yet handle images like your scenario above but now that I know that is something people would want it can be added to the backlog.

Have a look at:
* https://github.com/lsd-consulting/lsd-interceptors [useful for component / acceptance tests]
* https://github.com/lsd-consulting/lsd-distributed-interceptors [useful for full e2e tests]
* https://github.com/lsd-consulting/lsd-core [used by all the other libs to generate the report]
* https://github.com/lsd-consulting/lsd-junit5
* https://github.com/lsd-consulting/lsd-cucumber

Some of the READMEs need some serious work but hopefully it gives you an idea of what is available.

**Comment by ryantaplin** [comment]
Hey Nick,

Sorry I completely forgot about this!

I think the team may have fixed it another way, i haven't touched the project using screenshots in the captured outputs for a little while.

On a side note; I'll  try to take a look at setting up the new lsd stuff in one of my mini side projects and see whether it fits our needs and be whether it would a suitable replacement for existing/new projects.

Thanks for taking the time to reply!
